version: 2.1

orbs:
  architect: giantswarm/architect@0.10.0


workflows:
  version: 2
  build:
    jobs:
      - architect/go-build:
          name: build-admission-controller
          context: architect
          binary: admission-controller
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          name: push-admission-controller-to-quay
          context: architect
          image: "quay.io/giantswarm/admission-controller"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - build-admission-controller
          # Needed to trigger job also on git tag.
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          name: push-admission-controller-to-aliyun
          context: architect
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/admission-controller"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          requires:
            - build-admission-controller
          # Needed to trigger job only on git tag.
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          name: push-admission-controller-to-control-plane-app-catalog
          context: architect
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "admission-controller"
          requires:
            - push-admission-controller-to-quay
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-admission-controller-to-aws-app-collection
          context: architect
          app_name: "admission-controller"
          app_collection_repo: "aws-app-collection"
          unique: "true"
          requires:
            - push-admission-controller-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
